### ISSUE TITLE
Landing page image/hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Arabic#4]
Hero image just needs to be sized and placed, please and thank you.

**Comment by pixelyunicorn** [comment]
Hero image: http://develop.cla.temple.edu/arabic/media/iStock_Arabic%20Nabawi%20Mosque.jpg

**Comment by ZMcGroarty** [comment]
![hero_arabic-min](https://cloud.githubusercontent.com/assets/15017242/23415312/e1cae9cc-fdac-11e6-8590-9395d99f5bc1.png)

**Comment by CVE82** [comment]
Awesome, thank you Zac!
