### ISSUE TITLE
Arabic Hero Image

### ISSUE THREAD

**Issue by ZMcGroarty** [TULiberalArts/Arabic#5]
![hero_arabic-min](https://cloud.githubusercontent.com/assets/15017242/24005289/f7e59696-0a3e-11e7-8a9a-a281ff5ee046.png)

**Comment by CVE82** [comment]
This is awesome thank you! I totally thought you had done these, and you did lol  Thanks again!

**Comment by CVE82** [comment]
Victor, can you push this image?

**Comment by CVE82** [comment]
Done!
