### ISSUE TITLE
Delete Next Stops page

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Arabic#7]

**Comment by pixelyunicorn** [comment]
FYI This leaves us only with 1 page of content (for now), which is the homepage.

**Comment by CVE82** [comment]
Please don't delete this page, I just read re-added Thursday. Thanks!



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by zepstein** [comment]
Let's talk about what we're doing with these pages. If a program doesn't have any information appropriate for Next Stops that is specific to them, I do not think we should have a page. I don't want to have the same, generic college copy on these pages.

**Comment by tu-chill** [comment]
closing this and referencing issue #9
